name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Generate Official Android Platform
        run: |
          # مسح أي مجلد أندرويد قديم
          rm -rf android
          
          # إنشاء مشروع فلاتر مؤقت نظيف في الخلفية للحصول على ملفات الأندرويد الرسمية
          cd ..
          flutter create temp_project --org com.mihrab.app --platforms android
          
          # نقل مجلد الأندرويد الرسمي والكامل لمشروعنا
          cp -r temp_project/android mihrab-app/
          cd mihrab-app

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mihrab-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
